name       : llvm
version    : 11.1.0
release    : 77
source     :
    - https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/llvm-11.1.0.src.tar.xz : ce8508e318a01a63d4e8b3090ab2ded3c598a50258cc49e2625b9120d4c03ea5
    - https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/clang-11.1.0.src.tar.xz : 0a8288f065d1f57cb6d96da4d2965cbea32edc572aa972e466e954d17148558b
    - https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/compiler-rt-11.1.0.src.tar.xz : def1fc00c764cd3abbba925c712ac38860a756a43b696b291f46fee09e453274
    - https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/lld-11.1.0.src.tar.xz : 017a788cbe1ecc4a949abf10755870519086d058a2e99f438829aef24f0c66ce
    - https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/clang-tools-extra-11.1.0.src.tar.xz : 76707c249de7a9cde3456b960c9a36ed9bbde8e3642c01f0ef61a43d61e0c1a2
    - https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/libcxx-11.1.0.src.tar.xz : bb233d250ed7eaa05c73eaf81ef0f9ee3fac9d8fc0c3d38a7a7383f82ed6f8e5
    - https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/libcxxabi-11.1.0.src.tar.xz : 143193ed80f8fa4d85211d6704a90789fb36aa65b69fd0c382a9f05ec370ecab
    - https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/openmp-11.1.0.src.tar.xz : d187483b75b39acb3ff8ea1b7d98524d95322e3cb148842957e9b0fbb866052e
homepage   : http://llvm.org/
license    : Apache-2.0-with-LLVM-exception
summary    :
    - Low Level Virtual Machine (Reusable compiler and toolchains)
    - clang : Clang Compiler frontend to LLVM
    - clang-devel : Development files for building clang plugins
    - clang-32bit : 32bit libraries for clang
component  :
    - programming
    - clang : programming
debug      : no
emul32     : yes
libsplit   : no
clang      : yes
builddeps  :
    - pkgconfig32(libelf)
    - pkgconfig32(libffi)
    - pkgconfig32(libxml-2.0)
    - pkgconfig(libedit)
    - doxygen
    - glibc-32bit-devel
    - libgcc-32bit
    - llvm-32bit-devel
    - python-recommonmark
    - swig
    - zlib-32bit-devel
rundeps    :
    - clang :
        - llvm-devel
    - clang-devel :
        - llvm-clang
    - clang-32bit-devel :
        - llvm-clang-32bit
        - llvm-clang-devel
description: |
    The LLVM package contains a collection of modular and reusable compiler and toolchain technologies. The Low Level Virtual Machine (LLVM) Core libraries provide a modern source and target-independent optimizer, along with code generation support for many popular CPUs (as well as some less common ones!). These libraries are built around a well specified code representation known as the LLVM intermediate representation ("LLVM IR").
patterns   :
    - 32bit-devel :
        - /usr/bin/llvm-config32
        - /usr/include/llvm/Config/llvm-config-32.h
        - /usr/lib32/cmake/llvm
    - clang-32bit :
        - /usr/lib32/libclang*.so*
        - /usr/lib32/SampleAnalyzerPlugin.so
        - /usr/lib32/CheckerOptionHandlingAnalyzerPlugin.so
        - /usr/lib32/CheckerDependencyHandlingAnalyzerPlugin.so
        - /usr/lib32/liblldb*.so*
        - /usr/lib32/lib*omp*.so*
    - clang-32bit-devel :
        - /usr/lib32/clang
        - /usr/lib32/cmake/clang
        - /usr/lib32/libclang*.a
        - /usr/lib32/liblldb*.a
    - clang-devel :
        - /usr/include/clang*
        - /usr/include/lld*
        - /usr/include/openmp*
        - /usr/lib64/libclang*.a
    - clang :
        - /usr/bin
        - /usr/libexec
        - /usr/lib64/clang
        - /usr/lib64/libclang*.so*
        - /usr/lib64/SampleAnalyzerPlugin.so
        - /usr/lib64/CheckerOptionHandlingAnalyzerPlugin.so
        - /usr/lib64/CheckerDependencyHandlingAnalyzerPlugin.so
        - /usr/share/man/*/*clang*
        - /usr/share/man/*/*scan-build*
        - /usr/share/llvm/cmake
        - /usr/share/clang
        - /usr/share/opt-viewer
        - /usr/share/scan-build
        - /usr/share/scan-view
    - devel :
        - /usr/bin/FileCheck
        - /usr/bin/bugpoint
        - /usr/bin/count
        - /usr/bin/dsymutil
        - /usr/bin/lli*
        - /usr/bin/llc*
        - /usr/bin/llvm*
        - /usr/bin/not
        - /usr/bin/obj2yaml
        - /usr/bin/opt
        - /usr/bin/sancov
        - /usr/bin/sanstats
        - /usr/bin/verify-uselistorder
        - /usr/bin/yaml-bench
        - /usr/bin/yaml2obj
        - /usr/share/llvm/cmake
replaces   :
    - clang : clang
    - clang-devel : clang-devel
environment: |
    # Decontaminate build environment
    unset LDFLAGS
    unset LD_AS_NEEDED

    # Set build flags
    if [[ -z "${EMUL32BUILD}" ]]; then
        export _LLVM_TRIPLE="%HOST%"
        export _LLVM_ARCH="x86_64"
        export _LLVM_FLAGS_FINAL="-march=x86-64 -mtune=generic -O3 -fstack-protector -pipe -DNDEBUG"
        export CC=gcc
        export CXX=g++
    else
        export _LLVM_TRIPLE="i686-pc-linux-gnu"
        export _LLVM_ARCH="i686"
        export _LLVM_FLAGS_FINAL="-march=i686 -msse2 -mtune=generic -O3 -fstack-protector -pipe -DNDEBUG -m32"
        export CC="gcc -m32"
        export CXX="g++ -m32"
    fi
setup      : |
    # llvm patches
    %patch -p1 < $pkgfiles/0001-llvm-Let-the-linker-find-the-correct-ffi-as-cmake-br.patch

    # Mesa shader cache may fail to compile without this
    %patch -p1 < $pkgfiles/amdgpu-avoid-an-illegal-operand-in-si-shrink-instr.patch

    mkdir -p tools

    # Set up our tools (cfe)
    tar xf $sources/clang-${version}.src.tar.xz -C tools
    mv tools/clang-${version}.src tools/clang

    # Set up compiler-rt
    tar xf $sources/compiler-rt-${version}.src.tar.xz -C projects
    mv projects/compiler-rt-${version}.src projects/compiler-rt

    # Set up openmp
    tar xf $sources/openmp-${version}.src.tar.xz -C projects
    mv projects/openmp-${version}.src projects/openmp

    # Patch cfe for Solus specific options
    pushd tools/clang
        %patch -p1 < $pkgfiles/0001-cfe-Use-correct-Solus-multilib-paths.patch
        %patch -p1 < $pkgfiles/0002-cfe-Use-the-GNU-hash-style-for-Solus-binary-build-id.patch
        %patch -p1 < $pkgfiles/0001-Enable-stack-protector-strong-by-default.patch
    popd

    if [[ -z "${EMUL32BUILD}" ]]; then
        # Set up clang-tools-extra
        tar xf $sources/clang-tools-extra-${version}*.src.tar.xz -C tools/clang/tools
        mv tools/clang/tools/clang-tools-extra-${version}*.src tools/clang/tools/extra

        # Set up lld
        tar xf $sources/lld-${version}.src.tar.xz -C tools
        mv tools/lld-${version}.src tools/lld

        # Pull lld in line with binutils linkers for consistency
        pushd tools/lld
            %patch -p1 < $pkgfiles/0001-Enable-as-needed-with-LD_AS_NEEDED-variable.patch
            %patch -p1 < $pkgfiles/0002-Make-gnuhash-the-default-when-not-specified.patch
        popd
    fi

    # Now set up all of the projects (libcxx, libcxxabi)
    mkdir -p projects
    for project in libcxx libcxxabi ; do
        tar xf $sources/${project}-${version}.src.tar.xz -C projects
        mv projects/${project}-${version}.src projects/${project}
    done

    # Set up stage2 final flags
    export CFLAGS="$_LLVM_FLAGS_FINAL"
    export CXXFLAGS="$_LLVM_FLAGS_FINAL"

    # Configure
    mkdir solusBuildDir
    pushd solusBuildDir
    cmake -G Ninja .. \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_C_FLAGS_RELEASE="$CFLAGS" \
        -DCMAKE_CXX_FLAGS_RELEASE="$CXXFLAGS" \
        -DCMAKE_INSTALL_PREFIX=/usr \
        -DCLANG_DEFAULT_LINKER="lld" \
        -DCLANG_DEFAULT_OBJCOPY="llvm-objcopy" \
        -DLLVM_INSTALL_UTILS=ON \
        -DLLVM_LIBDIR_SUFFIX=%LIBSUFFIX% \
        -DLLVM_TARGET_ARCH=$_LLVM_ARCH \
        -DLLVM_BINUTILS_INCDIR=/usr/include \
        -DLLVM_DEFAULT_TARGET_TRIPLE=$_LLVM_TRIPLE \
        -DLLVM_ENABLE_FFI=ON \
        -DLLVM_ENABLE_ZLIB=ON \
        -DLLVM_ENABLE_RTTI=ON \
        -DLLVM_ENABLE_ASSERTIONS=OFF \
        -DENABLE_LINKER_BUILD_ID=ON \
        -DLLVM_ENABLE_PIC=ON \
        -DLLVM_TARGETS_TO_BUILD="host;AMDGPU;BPF" \
        -DLLVM_BUILD_LLVM_DYLIB=ON \
        -DLLVM_LINK_LLVM_DYLIB=ON \
        -DLLVM_BUILD_DOCS=ON \
        -DLLVM_ENABLE_SPHINX=ON \
        -DSPHINX_EXECUTABLE="/usr/bin/sphinx-build" \
        -DSPHINX_OUTPUT_MAN=ON \
        -DSPHINX_OUTPUT_HTML=OFF \
        -DSPHINX_WARNINGS_AS_ERRORS=OFF \
        -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD="AVR"

    popd
build      : |
    %ninja_build -v docs-llvm-man
install    : |
    %ninja_install -v docs-llvm-man
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        mv $installdir/usr/bin/llvm-config{,32}
    fi
    mv $installdir/usr/include/llvm/Config/llvm-config.h $installdir/usr/include/llvm/Config/llvm-config-%LIBSUFFIX%.h

    # Do NOT include libgomp*, it will conflict with libgomp
    rm $installdir/%libdir%/libgomp.*

    # Only execute for 64bit build
    if [[ -z "${EMUL32BUILD}" ]]; then
        install -d -D -m 00755 $installdir/%libdir%/bfd-plugins
        ln -sv ../LLVMgold.so $installdir/%libdir%/bfd-plugins/.
        # Finally add our compatibility header
        install -m 00644 $pkgfiles/llvm-config.h $installdir/usr/include/llvm/Config/llvm-config.h
    fi
